# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrado',
            name='sexo',
            field=models.CharField(blank=True, choices=[('F', 'FEMENINO'), ('M', 'MASCULINO')], max_length=1, null=True),
        ),
    ]
