# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 17:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.IntegerField(blank=True, null=True, unique=True)),
                ('nombres', models.CharField(max_length=50)),
                ('paterno', models.CharField(max_length=20, verbose_name='Apellido Paterno')),
                ('materno', models.CharField(blank=True, max_length=20, null=True, verbose_name='Apellido Materno')),
                ('del_marido', models.CharField(blank=True, max_length=20, null=True, verbose_name='Apellido del Marido')),
                ('fecha_nac', models.DateField()),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('celular', models.IntegerField(blank=True, null=True)),
                ('direccion', models.CharField(blank=True, max_length=50, null=True)),
                ('sexo', models.CharField(choices=[('F', 'FEMENINO'), ('M', 'MASCULINO')], max_length=3)),
                ('ocupacion', models.CharField(blank=True, max_length=50, null=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Registrado',
        ),
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('registrado', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='registrar.Persona')),
                ('AEM', multiselectfield.db.fields.MultiSelectField(choices=[('S', 'SI'), ('N', 'NO')], max_length=3, null=True, verbose_name='sabes lo que es?')),
                ('loHace', multiselectfield.db.fields.MultiSelectField(choices=[('S', 'SI'), ('N', 'NO')], max_length=3, null=True, verbose_name='Lo haces?')),
                ('p2', multiselectfield.db.fields.MultiSelectField(choices=[('S', 'SI'), ('N', 'NO'), ('NS', 'NOSE')], max_length=6, null=True, verbose_name='Alguna vez sentiste un bulto en el pecho?')),
                ('p3', multiselectfield.db.fields.MultiSelectField(choices=[('R', 'REGULARMENTE'), ('A', 'A veces'), ('NU', 'NUNCA')], max_length=6, null=True, verbose_name='Alguna vez consultaste por un problema de la mama?')),
                ('p4', multiselectfield.db.fields.MultiSelectField(choices=[('S', 'SI'), ('N', 'NO')], max_length=3, null=True, verbose_name='Alguna vez te hiciste Mamografia')),
                ('p5', multiselectfield.db.fields.MultiSelectField(choices=[('S', 'SI'), ('N', 'NO')], max_length=3, null=True, verbose_name='Alguna vez te hiciste Ecografia Mamaria?')),
                ('p6', multiselectfield.db.fields.MultiSelectField(choices=[('S', 'SI'), ('N', 'NO')], max_length=3, null=True, verbose_name='Alguien la familia alguna vez tuvo cancer de mama?')),
                ('p7', multiselectfield.db.fields.MultiSelectField(choices=[('S', 'SI'), ('N', 'NO')], max_length=3, null=True, verbose_name='Conoces a alguien que haya tenido cancer de mama?')),
            ],
        ),
        migrations.CreateModel(
            name='Mamografia',
            fields=[
                ('registrado', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='registrar.Persona')),
                ('mamoDespi', models.CharField(blank=True, max_length=100, null=True, verbose_name='Mamografia despistaje')),
                ('mamoDiag', models.CharField(blank=True, max_length=100, null=True, verbose_name='Mamografia Diagnostica')),
                ('nodulo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nodulo')),
                ('antecedentes', models.CharField(blank=True, max_length=100, null=True, verbose_name='Antecedentes familiares')),
                ('otros', models.CharField(blank=True, max_length=100, null=True, verbose_name='Otros factores de riesgo')),
                ('densidad', multiselectfield.db.fields.MultiSelectField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], max_length=7, null=True, verbose_name='Densidad')),
                ('descripcion', models.CharField(max_length=100, null=True, verbose_name='Descripcion')),
                ('birads', multiselectfield.db.fields.MultiSelectField(choices=[('0', 'Estudio insuficiente - Se recomienda'), ('1', 'Normal'), ('2', 'Anormal,Benigno'), ('3', 'Anormal, probablemente benigno'), ('4a', 'Anormal, probablemente benigno (baja)'), ('4b', 'Anormal, probablemente benigno(intermedia) '), ('4c', 'Anormal, probablemente benigno(alta)'), ('5', 'Anormal, maligno'), ('6', 'Anorma, maligno ya biopsiado')], max_length=20, null=True, verbose_name='BIRADS')),
                ('eg', models.CharField(max_length=100, null=True, verbose_name='EG')),
                ('hallazgos', models.CharField(max_length=100, null=True, verbose_name='Hallazgos?, si o no y descripcion')),
            ],
        ),
    ]
