# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 18:38
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0002_auto_20170316_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encuesta',
            name='registrado',
        ),
        migrations.AddField(
            model_name='persona',
            name='AEM',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('S', 'SI'), ('N', 'NO')], max_length=3, null=True, verbose_name='sabes lo que es?'),
        ),
        migrations.AddField(
            model_name='persona',
            name='loHace',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('S', 'SI'), ('N', 'NO')], max_length=3, null=True, verbose_name='Lo haces?'),
        ),
        migrations.AddField(
            model_name='persona',
            name='p2',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('S', 'SI'), ('N', 'NO'), ('NS', 'NOSE')], max_length=6, null=True, verbose_name='Alguna vez sentiste un bulto en el pecho?'),
        ),
        migrations.AddField(
            model_name='persona',
            name='p3',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('R', 'REGULARMENTE'), ('A', 'A veces'), ('NU', 'NUNCA')], max_length=6, null=True, verbose_name='Alguna vez consultaste por un problema de la mama?'),
        ),
        migrations.AddField(
            model_name='persona',
            name='p4',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('S', 'SI'), ('N', 'NO')], max_length=3, null=True, verbose_name='Alguna vez te hiciste Mamografia'),
        ),
        migrations.AddField(
            model_name='persona',
            name='p5',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('S', 'SI'), ('N', 'NO')], max_length=3, null=True, verbose_name='Alguna vez te hiciste Ecografia Mamaria?'),
        ),
        migrations.AddField(
            model_name='persona',
            name='p6',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('S', 'SI'), ('N', 'NO')], max_length=3, null=True, verbose_name='Alguien la familia alguna vez tuvo cancer de mama?'),
        ),
        migrations.AddField(
            model_name='persona',
            name='p7',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('S', 'SI'), ('N', 'NO')], max_length=3, null=True, verbose_name='Conoces a alguien que haya tenido cancer de mama?'),
        ),
        migrations.DeleteModel(
            name='Encuesta',
        ),
    ]
