# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0003_auto_20170323_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='bulto',
            field=models.BooleanField(choices=[(True, 'Si'), (False, 'No')], default=False, verbose_name='Alguna vez sentiste un bulto en el pecho?'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='loHace',
            field=models.BooleanField(choices=[('S', 'SI'), ('N', 'NO')], default=None, verbose_name='Lo haces?'),
            preserve_default=False,
        ),
    ]
