# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0005_auto_20170327_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='p2',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='p3',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='p4',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='p5',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='p6',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='p7',
        ),
        migrations.AddField(
            model_name='persona',
            name='cancer_mama',
            field=models.BooleanField(choices=[(True, 'Si'), (False, 'No')], default=False, verbose_name='Alguien en la familia alguna vez tuvo cancer de mama?'),
        ),
        migrations.AddField(
            model_name='persona',
            name='eco_mama',
            field=models.BooleanField(choices=[(True, 'Si'), (False, 'No')], default=False, verbose_name='Alguna vez te hiciste una ecografia mamaria?'),
        ),
        migrations.AddField(
            model_name='persona',
            name='hizo_mamo',
            field=models.BooleanField(choices=[(True, 'Si'), (False, 'No')], default=False, verbose_name='Alguna vez te hiciste Mamografia?'),
        ),
        migrations.AddField(
            model_name='persona',
            name='mama_detalle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='tenido_cancer',
            field=models.BooleanField(choices=[(True, 'Si'), (False, 'No')], default=False, verbose_name='Conoces a alguien que haya tenido cancer de mama?'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='AEM',
            field=models.BooleanField(choices=[(True, 'Si'), (False, 'No')], default=False, verbose_name='AUTOEXAMEN MAMARIO, sabes lo que es?'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='loHace',
            field=models.BooleanField(choices=[('R', 'REGULARMENTE'), ('A', 'A veces'), ('NU', 'NUNCA')], default='NU', verbose_name='Lo haces?'),
        ),
    ]
