# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0007_auto_20170328_1433'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mamografia',
            options={'verbose_name': 'Mamografia', 'verbose_name_plural': 'Mamografias'},
        ),
        migrations.AlterModelOptions(
            name='persona',
            options={'verbose_name': 'Ficha de Paciente', 'verbose_name_plural': 'Ficha de Pacientes'},
        ),
        migrations.AddField(
            model_name='mamografia',
            name='des_birads',
            field=models.CharField(max_length=150, null=True, verbose_name='Birads'),
        ),
        migrations.AlterField(
            model_name='mamografia',
            name='birads',
            field=models.CharField(choices=[('0', 'Estudio insuficiente - Se recomienda'), ('1', 'Normal'), ('2', 'Anormal,Benigno'), ('3', 'Anormal, probablemente benigno'), ('4a', 'Anormal, probablemente benigno (baja)'), ('4b', 'Anormal, probablemente benigno(intermedia) '), ('4c', 'Anormal, probablemente benigno(alta)'), ('5', 'Anormal, maligno'), ('6', 'Anorma, maligno ya biopsiado')], max_length=3, null=True, verbose_name='BIRADS'),
        ),
        migrations.AlterField(
            model_name='mamografia',
            name='densidad',
            field=models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], max_length=3, null=True, verbose_name='Densidad'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='AEM',
            field=models.CharField(choices=[(True, 'Si'), (False, 'No')], default=False, max_length=3, verbose_name='Sabes lo que es?'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='bulto_pecho',
            field=models.CharField(choices=[(True, 'Si'), (False, 'No'), (None, 'No se')], max_length=3, verbose_name='Alguna vez sentiste un bulto en el pecho?'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='cancer_mama',
            field=models.CharField(choices=[(True, 'Si'), (False, 'No')], default=False, max_length=3, verbose_name='Alguien en la familia alguna vez tuvo cancer de mama?'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='eco_mama',
            field=models.CharField(choices=[(True, 'Si'), (False, 'No')], default=False, max_length=3, verbose_name='Alguna vez te hiciste una ecografia mamaria?'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='hizo_mamo',
            field=models.CharField(choices=[(True, 'Si'), (False, 'No')], default=False, max_length=3, verbose_name='Alguna vez te hiciste Mamografia?'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='loHace',
            field=models.CharField(choices=[('R', 'REGULARMENTE'), ('A', 'A veces'), ('NU', 'NUNCA')], default='NU', max_length=3, verbose_name='Lo haces?'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='problema_mama',
            field=models.CharField(choices=[(True, 'Si'), (False, 'No')], default=False, max_length=3, verbose_name='Alguna vez consultaste por un problema de la mama?'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='tenido_cancer',
            field=models.CharField(choices=[(True, 'Si'), (False, 'No')], default=False, max_length=3, verbose_name='Conoces a alguien que haya tenido cancer de mama?'),
        ),
    ]
